# This is just to run a test environment with a local database

version: '3.7'

services:
  db:
    image: mariadb:latest

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

    volumes:
      - db_data:/var/lib/mysql

    ports:
      - "3306:3306"


volumes:
  db_data:
    driver: local
